version: "3.8"

services:
  incoming-nordic:
    build:
      context: ./src
      dockerfile: ./incoming-nordic/Dockerfile
    image: incoming-nordic:latest
    ports:
      - "80:19000"
    deploy:
      replicas: 1
  create-abstracts:
    build:
      context: ./src
      dockerfile: ./create-abstracts/Dockerfile
    image: create-abstracts:latest
    ports:
      - "80:19001"
    deploy:
      replicas: 1
  daisy202-to-distribution:
    build:
      context: ./src
      dockerfile: ./daisy202-to-distribution/Dockerfile
    image: daisy202-to-distribution:latest
    ports:
      - "80:19002"
    deploy:
      replicas: 1
  insert-metadata-braille:
    build:
      context: ./src
      dockerfile: ./insert-metadata-braille/Dockerfile
    image: insert-metadata-braille:latest
    ports:
      - "80:19003"
    deploy:
      replicas: 1
  insert-metadata-daisy202:
    build:
      context: ./src
      dockerfile: ./insert-metadata-daisy202/Dockerfile
    image: insert-metadata-daisy202:latest
    ports:
      - "80:19004"
    deploy:
      replicas: 1
  insert-metadata-xhtml:
    build:
      context: ./src
      dockerfile: ./insert-metadata-xhtml/Dockerfile
    image: insert-metadata-xhtml:latest
    ports:
      - "80:19005"
    deploy:
      replicas: 1
  magazines-to-validation:
    build:
      context: ./src
      dockerfile: ./magazines-to-validation/Dockerfile
    image: magazines-to-validation:latest
    ports:
      - "80:19006"
    deploy:
      replicas: 1
  newsletter-to-braille:
    build:
      context: ./src
      dockerfile: ./newsletter-to-braille/Dockerfile
    image: newsletter-to-braille:latest
    ports:
      - "80:19007"
    deploy:
      replicas: 1
  newspaper-schibsted:
    build:
      context: ./src
      dockerfile: ./newspaper-schibsted/Dockerfile
    image: newspaper-schibsted:latest
    ports:
      - "80:19008"
    deploy:
      replicas: 1
  nlbpub-to-docx:
    build:
      context: ./src
      dockerfile: ./nlbpub-to-docx/Dockerfile
    image: nlbpub-to-docx:latest
    ports:
      - "80:19009"
    deploy:
      replicas: 1
  nlbpub-to-epub:
    build:
      context: ./src
      dockerfile: ./nlbpub-to-epub/Dockerfile
    image: nlbpub-to-epub:latest
    ports:
      - "80:19010"
    deploy:
      replicas: 1
  nlbpub-to-html:
    build:
      context: ./src
      dockerfile: ./nlbpub-to-html/Dockerfile
    image: nlbpub-to-html:latest
    ports:
      - "80:19011"
    deploy:
      replicas: 1
  nlbpub-to-narration-epub:
    build:
      context: ./src
      dockerfile: ./nlbpub-to-narration-epub/Dockerfile
    image: nlbpub-to-narration-epub:latest
    ports:
      - "80:19012"
    deploy:
      replicas: 1
  nlbpub-to-pef:
    build:
      context: ./src
      dockerfile: ./nlbpub-to-pef/Dockerfile
    image: nlbpub-to-pef:latest
    ports:
      - "80:19013"
    deploy:
      replicas: 1
  nlbpub-to-tts-dtbook:
    build:
      context: ./src
      dockerfile: ./nlbpub-to-tts-dtbook/Dockerfile
    image: nlbpub-to-tts-dtbook:latest
    ports:
      - "80:19014"
    deploy:
      replicas: 1
  nordic-epub-to-nlbpub:
    build:
      context: ./src
      dockerfile: ./nordic-epub-to-nlbpub/Dockerfile
    image: nordic-epub-to-nlbpub:latest
    ports:
      - "80:19015"
    deploy:
      replicas: 1
  prepare-for-braille:
    build:
      context: ./src
      dockerfile: ./prepare-for-braille/Dockerfile
    image: prepare-for-braille:latest
    ports:
      - "80:19016"
    deploy:
      replicas: 1
  prepare-for-docx:
    build:
      context: ./src
      dockerfile: ./prepare-for-docx/Dockerfile
    image: prepare-for-docx:latest
    ports:
      - "80:19017"
    deploy:
      replicas: 1
  prepare-for-ebook:
    build:
      context: ./src
      dockerfile: ./prepare-for-ebook/Dockerfile
    image: prepare-for-ebook:latest
    ports:
      - "80:19018"
    deploy:
      replicas: 1
  statped-nlbpub-to-nlbpub:
    build:
      context: ./src
      dockerfile: ./statped-nlbpub-to-nlbpub/Dockerfile
    image: statped-nlbpub-to-nlbpub:latest
    ports:
      - "80:19019"
    deploy:
      replicas: 1
  